homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

std_add:
    path:     /std/add/{name}/{indexno}/{icbc}/{gender}/{birthyear}
    prefix:   /app
    defaults:  { _controller: AppBundle:Student:add }

std_view_all:
    path:     /std/view/all
    defaults:  { _controller: AppBundle:Student:list }
